### PR TITLE
Add delete action in time tracking

### PR DESCRIPTION
**Pull request by JorenSaey**
ADDED
  - delete action in time tracking domain

UPDATED
  - tests for time tracking domain
  - version number

### CODE REVIEW

**Comment by duivvv** [comment]
👍 

Just asking around why it's not on https://developer.teamleader.eu/#/reference/time-tracking before merging it.

**Comment by WouterSioen** [comment]
This will documented soon, so no reason to block!

**Comment by duivvv** [comment]
@JorenSaey 

there are valid endpoints that are not on https://developer.teamleader.eu/#/reference/time-tracking but used internally. We are not supporting those in sdk-js.

Was just wondering if it was one of those 🙂

**Comment by JorenSaey** [comment]
Oh I didn't know that :) thanks for clarifying that :)

**Comment by duivvv** [comment]
merged and released as `1.5.0`

**Pull request merged**
